# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_ChatServer(object):
    def setupUi(self, ChatServer):
        ChatServer.setObjectName("ChatServer")
        ChatServer.resize(831, 465)
        ChatServer.setMinimumSize(QtCore.QSize(831, 465))
        ChatServer.setMaximumSize(QtCore.QSize(831, 465))
        ChatServer.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(ChatServer)
        self.centralwidget.setObjectName("centralwidget")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(430, 427, 151, 31))
        self.startBtn.setObjectName("startBtn")
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setGeometry(QtCore.QRect(632, 427, 141, 31))
        self.stopBtn.setObjectName("stopBtn")
        self.stopBtn.setEnabled(False)
        self.users = QtWidgets.QTableWidget(self.centralwidget)
        self.users.setGeometry(QtCore.QRect(30, 220, 311, 192))
        self.users.setObjectName("users")
        self.users.setColumnCount(4)
        self.users.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.users.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.users.setItem(0, 3, item)
        self.logView = QtWidgets.QTextBrowser(self.centralwidget)
        self.logView.setGeometry(QtCore.QRect(380, 20, 421, 391))
        self.logView.setObjectName("logView")
        self.serverUsage = QtWidgets.QTextBrowser(self.centralwidget)
        self.serverUsage.setGeometry(QtCore.QRect(30, 20, 311, 192))
        self.serverUsage.setObjectName("serverUsage")
        ChatServer.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatServer)
        QtCore.QMetaObject.connectSlotsByName(ChatServer)

    def retranslateUi(self, ChatServer):
        _translate = QtCore.QCoreApplication.translate
        ChatServer.setWindowTitle(_translate("ChatServer", "Chat Server"))
        self.startBtn.setText(_translate("ChatServer", "Start Server"))
        self.stopBtn.setText(_translate("ChatServer", "Stop Server"))
        item = self.users.verticalHeaderItem(0)
        item.setText(_translate("ChatServer", "1"))
        item = self.users.horizontalHeaderItem(0)
        item.setText(_translate("ChatServer", "Name"))
        item = self.users.horizontalHeaderItem(1)
        item.setText(_translate("ChatServer", "IP"))
        item = self.users.horizontalHeaderItem(2)
        item.setText(_translate("ChatServer", "Port"))
        item = self.users.horizontalHeaderItem(3)
        item.setText(_translate("ChatServer", "Active time(s)"))
        __sortingEnabled = self.users.isSortingEnabled()
        self.users.setSortingEnabled(False)
        item = self.users.item(0, 0)
        item.setText(_translate("ChatServer", "Jade"))
        item = self.users.item(0, 1)
        item.setText(_translate("ChatServer", "192.168.0.5"))
        item = self.users.item(0, 2)
        item.setText(_translate("ChatServer", "25565"))
        item = self.users.item(0, 3)
        item.setText(_translate("ChatServer", "458"))
        self.users.setSortingEnabled(__sortingEnabled)
